 #####  ######
#     # #     # 
#       #     # 
 #####  ######
     # #     #
#     # #     #
 #####  ######

name: SpawnerBlocker
main: sx.cur.omnivion.spawnerblocker.SpawnerBlocker
version: 1.1.0
load: POSTWORLD
database: false
description: SpawnerBlockerForSomeGuyOnSpigot
author: Omnivion
website: http://cur.sx

permissions:
  spawnerblocker.allow:
    description: Allows placement of spawners in the Nether
    default: op